# set floating (nontiling) for app needing it:
for_window [app_id="blueman-manager"] floating enable,  resize set width 40 ppt height 40 ppt

# set floating (nontiling) for special apps:
for_window [app_id="pavucontrol" ] floating enable, resize set width 30 ppt height 40 ppt
