include colors

# Window decorations:    border,   background,  text,     indicator, child-border
client.focused           $blue     $base        $text      $blue      $blue
client.focused_inactive  $mantle   $base        $text      $mantle    $mantle
client.unfocused         $mantle   $base        $text      $mantle    $mantle
client.urgent            $peach    $base        $peach     $overlay0  $peach
client.placeholder       $base     $base        $text      $overlay0  $overlay0
client.background        $base

# Gaps between windows and screen edges
gaps inner 5
gaps outer 5

# Window borders
default_border pixel 3
smart_borders off

# Mouse focus behavior
focus_follows_mouse no
